SOURCE_WEIGHTS = {
    "Reuters": 1.5,
    "Bloomberg": 1.5,
    "Federal Reserve": 2.0,
    "ECB": 2.0,
    "TradingEconomics": 1.2,
    "Yahoo Finance": 1.0,
    "FXStreet": 1.0,
    "OilPrice": 1.3,
}

KEYWORD_BOOST = {
    "unexpected": 1.5,
    "hawkish": 1.4,
    "dovish": 1.4,
    "accelerates": 1.3,
    "slows": 1.3,
    "recession": 1.5,
    "rate hike": 1.5,
    "cut rates": 1.5,
    "inflation": 1.2,
    "jobs": 1.2,
    "unemployment": 1.2,
}

CURRENCY_IMPACTS = {
    "crude oil": ["CAD", "NOK"],
    "brent": ["CAD", "NOK"],
    "wti": ["CAD"],
    "natural gas": ["NOK", "CAD"],
    "iron ore": ["AUD"],
    "copper": ["CLP", "AUD"],
    "aluminum": ["AUD"],
    "gold": ["XAU", "USD", "CHF"],
    "silver": ["XAG", "USD"],
    "GDP": ["USD", "EUR", "GBP", "JPY", "AUD", "CAD", "NZD"],
    "inflation": ["USD", "EUR", "GBP", "JPY", "AUD", "CAD", "NZD"],
    "interest rate": ["USD", "EUR", "GBP", "JPY", "AUD", "CAD", "NZD"],
    "soybeans": ["BRL", "ARS"],
    "iron ore": ["BRL"],
    "agriculture": ["BRL"],
    "China": ["BRL"],
    "commodity exports": ["BRL"],
    "emerging markets": ["BRL"],
    "Petrobras": ["BRL"],
    "BNDES": ["BRL"],
    "Copom": ["BRL"],
    "Selic": ["BRL"],
    "Brazil": ["BRL"],
    "Brasília": ["BRL"],
}
